<?php

/**
 * @file
 * Provide a form for an end user to change an Oracle database password
 * @license https://www.gnu.org/licenses/gpl-2.0.html GPL v2 or later
 */

/**
 * Implements hook_help().
 */
function oracle_password_help($path, $arg) {
  switch ($path) {
    case 'admin/help#oracle_password':
      return '<h3>' . t('About') . '</h3>' . '<p>' . t('The Oracle Password Change module will allow a user to change an Oracle database password.  Administrators can provide links which pass in default values for the database (d), username (u), and password (p) via querystring.') . '</p>';
      break;
  }
}

/**
 * Implements hook_permission().
 */
function oracle_password_permission() {
  return array(
    'access oracle password change' => array(
      'title' => t('Access Oracle password change'),
      'description' => t('Provide link to the Oracle password change form.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function oracle_password_menu() {
  // Action link
  $items['oracle_password'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('oracle_password_change_form'),
    'title' => 'Change Oracle Password',
    'access arguments' => array('access oracle password change'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_form().
 */
function oracle_password_change_form($node, &$form_state) {
  global $user;
  module_load_include('inc', 'forena', 'forena.common');

  $presets = drupal_get_query_parameters();

  $form = array();

  $form['overview'] = array(
    '#markup' => t('Enter your Oracle username, current password, and a new password to change your Oracle password.  This will not affect your Voyager password or your computer or email login.'),
    '#prefix' => '<p>',
    '#suffix' => '</p>',
  );

  $dboptions = array();
  $dbopt = '';
  $repos = Frx::RepoMan()->repositories;
  foreach ($repos as $name => $r) {
    $repo = Frx::RepoMan()->repository($name);
    // Forena 3.x if ($repo->db_type == 'oracle' && $repo->conf['uri']) {
    if ($repo->conf['data provider'] == 'FrxOracle' && $repo->conf['uri']) {
      $dboptions[$repo->conf['uri']] = $r['title'];
      if (isset($presets['d']) && stripos($repo->conf['uri'], $presets['d']) !== FALSE) {
        $dbopt = $repo->conf['uri'];
      }
    }
  }

  $form['oracle_password_database'] = array(
    '#title' => t('Database'),
    '#description' => t('Your Oracle database'),
    '#type' => ($dbopt ? 'hidden' : 'select'),
    '#options' => $dboptions,
    '#default_value' => ($dbopt ? $dbopt : NULL),
    '#required' => TRUE,
  );

  $form['oracle_password_user'] = array(
    '#title' => t('Username'),
    '#description' => t('Your Oracle Reports username'),
    '#type' => (isset($presets['u']) ? 'hidden' : 'textfield'),
    '#default_value' => (isset($presets['u']) ? $presets['u'] : $user->name),
    '#required' => TRUE,
  );

  $form['oracle_password_password'] = array(
    '#title' => t('Current Password'),
    '#description' => t('Your current Oracle Reports password'),
    '#type' => (isset($presets['p']) ? 'hidden' : 'password'),
    '#default_value' => (isset($presets['p']) ? $presets['p'] : ''),
    '#required' => TRUE,
  );

  $form['oracle_password_newpassword'] = array(
    '#title' => t('New Password'),
    '#description' => t('Your new Oracle Reports password'),
    '#type' => 'password',
    '#default_value' => '',
    '#required' => TRUE,
  );

  $form['oracle_password_newpassword_verify'] = array(
    '#title' => t('Verify Password'),
    '#description' => t('Verify your new Oracle Reports password'),
    '#type' => 'password',
    '#default_value' => '',
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#title' => t('Change Password'),
    '#description' => t('Submit the password change'),
    '#default_value' => 'Submit',
  );

  return $form;
}

/**
 * Validates the Oracle Password change form
 */
function oracle_password_change_form_validate($form, &$form_state) {
  // check existing form errors (missing fields)
  $missing_fields = form_get_errors();
  if (!$missing_fields) {
    // check to ensure new password entries match
    if ($form_state['values']['oracle_password_newpassword'] !== $form_state['values']['oracle_password_newpassword_verify']) {
      form_set_error('oracle_password_newpassword_verify', t('New passwords do not match'));
    } else {
      // if the form is complete and the new passwords match, we can try the connection
      $db = NULL;
      try {
        $db = oci_connect($form_state['values']['oracle_password_user'], $form_state['values']['oracle_password_password'], $form_state['values']['oracle_password_database']);
        // we could get an OCI error without an exception
        if ($e = oci_error()) {
          form_set_error('', t('Unable to connect to database:') . ' ' . $e['message']);
        }
      } catch (Exception $ex) {
        form_set_error('', t('Unable to connect to database:') . ' ' . $ex->getMessage());
      }
      // If we successfully connected, try the password change
      if ($db) {
        if ( oci_password_change($db, $form_state['values']['oracle_password_user'], $form_state['values']['oracle_password_password'], $form_state['values']['oracle_password_newpassword']) ) {
          // notify of success
          drupal_set_message(t('Successfully changed your Oracle password.')); 
        } else if ($e = oci_error($stmt)) {
          // warn of failure
          form_set_error('', t('Failed to change password:') . ' ' . $e['message']);
        }
      }
    }
  }
}

